TextInput_valid_properties = ['_cursor_blink', '_cursor_visual_height', '_cursor_visual_pos', '_editable', '_hint_text',
     '_hint_text_lines', '_ime_composition', '_ime_cursor', '_keyboard', '_lines', 'allow_copy',
     'auto_indent', 'background_active', 'background_color', 'background_disabled_normal',
     'background_normal', 'base_direction', 'border', 'center', 'center_x', 'center_y', 'children',
     'cls', 'cursor', 'cursor_blink', 'cursor_col', 'cursor_color', 'cursor_pos', 'cursor_row',
     'cursor_width', 'disabled', 'disabled_foreground_color', 'do_wrap', 'focus', 'focus_next',
     'focus_previous', 'focused', 'font_context', 'font_family', 'font_name', 'font_size',
     'foreground_color', 'halign', 'handle_image_left', 'handle_image_middle', 'handle_image_right',
     'height', 'hint_text', 'hint_text_color', 'ids', 'input_filter', 'input_type', 'is_focusable',
     'keyboard', 'keyboard_mode', 'keyboard_suggestions', 'line_height', 'line_spacing', 'lines_to_scroll',
     'minimum_height', 'motion_filter', 'multiline', 'opacity', 'padding', 'padding_x', 'padding_y',
     'parent', 'password', 'password_mask', 'pos', 'pos_hint', 'readonly', 'replace_crlf', 'right',
     'scroll_distance', 'scroll_from_swipe', 'scroll_timeout', 'scroll_x', 'scroll_y',
     'selection_color', 'selection_from', 'selection_text', 'selection_to', 'size',
     'size_hint', 'size_hint_max', 'size_hint_max_x', 'size_hint_max_y', 'size_hint_min',
     'size_hint_min_x', 'size_hint_min_y', 'size_hint_x', 'size_hint_y', 'tab_width', 'text',
     'text_language', 'text_validate_unfocus', 'top', 'unfocus_on_touch', 'use_bubble',
     'use_handles', 'width', 'write_tab', 'x', 'y']

Label_valid_properties = ['anchors', 'base_direction', 'bold', 'center', 'center_x', 'center_y', 'children',
                          'cls', 'color', 'disabled', 'disabled_color', 'disabled_outline_color', 'ellipsis_options',
                          'font_blended', 'font_context', 'font_direction', 'font_family', 'font_features', 'font_hinting',
                          'font_kerning', 'font_name', 'font_script_name', 'font_size', 'halign', 'height', 'ids',
                          'is_shortened', 'italic', 'limit_render_to_text_bbox', 'line_height', 'markup', 'max_lines',
                          'mipmap', 'motion_filter', 'opacity', 'outline_color', 'outline_width', 'padding', 'padding_x',
                          'padding_y', 'parent', 'pos', 'pos_hint', 'refs', 'right', 'shorten', 'shorten_from', 'size',
                          'size_hint', 'size_hint_max', 'size_hint_max_x', 'size_hint_max_y', 'size_hint_min', 'size_hint_min_x',
                          'size_hint_min_y', 'size_hint_x', 'size_hint_y', 'split_str', 'strikethrough', 'strip', 'text',
                          'text_language', 'text_size', 'texture', 'texture_size', 'top', 'underline', 'unicode_errors',
                          'valign', 'width', 'x', 'y']

